<?php
/**
 * @file
 * Contains smartservices_custom.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
/**
 * Implements hook_toolbar_alter().
 */
function smartservices_custom_toolbar_alter(&$items) {
	$current_route = \Drupal::routeMatch()->getRouteName();
	$current_theme_name = \Drupal::theme()->getActiveTheme()->getName();
	$theme_to_exclude_toolbar = array('smartservices' => 'smartservices');
	if ($theme_to_exclude_toolbar) {
		foreach ($theme_to_exclude_toolbar as $key => $theme_name) {
		  if ($theme_name == $current_theme_name) {
			unset($items['administration']);
			unset($items['shortcuts']);
			unset($items['admin_toolbar_tools']);
			unset($items['administration_search']);
			unset($items['user']);
			unset($items['devel']);
			unset($items['contextual']);
			unset($items['home']);
			unset($items['tour']);
			unset($items['toolbar_menu_site_menus']);
			
		  }
		}
	}
}
/**
 * Implements hook_form_alter().
 */
function smartservices_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	if (isset($form['promote']['#access'])) {
		$form['promote']['#access'] = FALSE;
	}
	if (isset($form['sticky']['#access'])) {
		$form['sticky']['#access'] = FALSE;
	}
	if (isset($form['menu']['#access'])) {
		$form['menu']['#access'] = FALSE;
	}
	if (isset($form['revision_log']['#access'])) {
		$form['revision_log']['#access'] = FALSE;
	}
	if($form_id == 'node_mobile_form' || $form_id == 'node_mobile_edit_form'){
		$form['actions']['submit']['#value'] = 'Recharge';
	}
	if($form_id == 'node_dth_form' || $form_id == 'node_dth_edit_form'){
		$form['actions']['submit']['#value'] = 'Recharge';
	}
	if($form_id == 'node_data_card_form' || $form_id == 'node_data_card_edit_form'){
		$form['actions']['submit']['#value'] = 'Recharge';
	}
	if($form_id == 'node_postpaid_form' || $form_id == 'node_postpaid_edit_form'){
		$form['actions']['submit']['#value'] = 'Recharge';
	}
	if($form_id == 'node_insurance_form' || $form_id == 'node_insurance_edit_form'){
		$form['actions']['submit']['#value'] = 'Recharge';
	}
	if($form_id == 'node_gas_form' || $form_id == 'node_gas_edit_form'){
		$form['actions']['submit']['#value'] = 'Recharge';
	}
	if ($form_state->getFormObject() instanceof \Drupal\Core\Entity\EntityFormInterface) {
		$entity_type = $form_state->getFormObject()->getEntity()->getEntityTypeId();
	}
	if(isset($entity_type)){
	  if($entity_type == 'node'){
		  foreach (array_keys($form['actions']) as $action) {
			if (isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
			  $form['actions'][$action]['#submit'][] = 'custom_form_submit_redirect';
			}
		  }
	  }
	}	
}
function custom_form_submit_redirect(&$form,  \Drupal\Core\Form\FormStateInterface $form_state) {
	$url = Url::fromRoute('system.admin_content');
	$form_state->setRedirectUrl($url);
}
/**
* Implementation of hook_node_presave().
*
*/

function smartservices_custom_node_presave(\Drupal\node\NodeInterface $node) {
	if ($node->getType() == 'mobile') {
		$node->title = 'Mobile Recharge';
	}
	if ($node->getType() == 'dth') {
		$node->title = 'DTH';
	}
	if ($node->getType() == 'data_card') {
		$node->title = 'Data Card';
	}
	if ($node->getType() == 'electricity') {
		$node->title = 'Electricity';
	}
	if ($node->getType() == 'gas') {
		$node->title = 'Gas';
	}
	if ($node->getType() == 'insurance') {
		$node->title = 'Insurance';
	}
	if ($node->getType() == 'new_dmr') {
		$node->title = 'New DMR';
	}
	if ($node->getType() == 'postpaid') {
		$node->title = 'Post Paid';
	}
	if ($node->getType() == 'utilities') {
		$node->title = 'Utilities';
	}
}
