<?php
/**
 * Implements hook_toolbar_alter().
 */
function smartservices_custom_toolbar_alter(&$items) {
	$current_route = \Drupal::routeMatch()->getRouteName();
	$current_theme_name = \Drupal::theme()->getActiveTheme()->getName();
	$theme_to_exclude_toolbar = array('smartservices' => 'smartservices');
	if ($theme_to_exclude_toolbar) {
		foreach ($theme_to_exclude_toolbar as $key => $theme_name) {
		  if ($theme_name == $current_theme_name) {
			unset($items['administration']);
			unset($items['shortcuts']);
			unset($items['admin_toolbar_tools']);
			unset($items['administration_search']);
			unset($items['user']);
			unset($items['devel']);
			unset($items['contextual']);
			unset($items['home']);
			unset($items['tour']);
			unset($items['toolbar_menu_site_menus']);
			
		  }
		}
	}
}
/**
 * Implements hook_form_alter().
 */
function smartservices_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
	if (isset($form['promote']['#access'])) {
		$form['promote']['#access'] = FALSE;
	}
	if (isset($form['sticky']['#access'])) {
		$form['sticky']['#access'] = FALSE;
	}
	if (isset($form['menu']['#access'])) {
		$form['menu']['#access'] = FALSE;
	}
	if (isset($form['revision_log']['#access'])) {
		$form['revision_log']['#access'] = FALSE;
	}
}
/**
* Implementation of hook_node_presave().
*
*/

function smartservices_custom_node_presave(\Drupal\node\NodeInterface $node) {
	if ($node->getType() == 'money_transfer') {
		$node->title = 'Money Transfer';
	}
}
